# Site settings
title: This is a test powowowowoww
email: rob@pixelstew.co.uk
description: > # this means to ignore newlines until "baseurl:"
  a site about front-end design and development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pixelstew.co.uk" # the base hostname & protocol for your site
twitter_username: pixelstewuk
github_username:  pixelstew
paginate: 4

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
